# Generated by Django 5.1.7 on 2025-03-27 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_user_id_address_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="id",
            new_name="address_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="id",
            new_name="payment_id",
        ),
    ]
